project1/algorithms/urls.py
from django.urls import path
from . import views


app_name = 'algorithms'
urlpatterns = [
    # path('crawling/problem_list/', views.problem_list_crawling),
    # path('crawling/problem_list/check/', views.check),
    # path('crawling/problem/<int:problem_num>/', views.problem_crawling3),
    # path('crawling/class_num', views.classes_num, name='classes_num')
    path('user/<user_pk>/', views.user_crawling, name='user_crawling'),
    path('crawling/solved/<user_pk>/', views.solved_crawling, name='solved_crawling'),
    path('solved/<user_pk>/', views.solved, name='solved'),
    path('index/', views.index, name='index'),
    path('create/', views.create, name='create'),

]

project1/challenges/urls.py
from django.urls import path
from . import views

app_name = 'challenges'

urlpatterns = [
    path('index/', views.index, name='index'),
    path('<int:challenge_pk>/', views.detail, name='detail'),
    path('<int:challenge_pk>/code/',views.code, name='code'),
    path('code/<int:code_pk>',views.watch, name='watch'),
]

project1/issues/urls.py
from django.urls import path
from . import views

app_name = 'issues'
urlpatterns = [
    path('', views.index, name='index'),
    path('<int:pk>/', views.detail, name='detail'),
    path('create/', views.create, name='create'),
    path('<int:pk>/delete/', views.delete, name='delete'),
    path('<int:pk>/update/', views.update, name='update'),
    path('<int:pk>/comments/', views.comments_create, name='comments_create'),
    path(
        '<int:issue_pk>/comments/<int:comment_pk>/delete/',
        views.comments_delete,
        name='comments_delete',
    ),
    path('<int:issue_pk>/likes/', views.likes, name='likes'),
    path('<int:issue_pk>/likes/<int:comment_pk>/', views.likes_comment, name='likes_comment'),
]

project1/main/urls.py
from django.urls import path
from . import views

app_name = 'main'
urlpatterns = [
    path('', views.index, name='index'),
    path('<int:pk>/', views.detail, name='detail'),
    path('test/', views.test, name='test'),
    path('test2/', views.test2, name='test2'),

]

project1/plans/urls.py
from django.urls import path
from . import views

app_name = 'plans'
urlpatterns = [
    path('', views.index, name='index'),
    path('<int:pk>/', views.detail, name='detail'),
    path('create/', views.create, name='create'),
    path('<int:pk>/delete/', views.delete, name='delete'),
    path('<int:pk>/update/', views.update, name='update'),
    path('<int:pk>/comments/', views.comments_create, name='comments_create'),
    path(
        '<int:plan_pk>/comments/<int:comment_pk>/delete/',
        views.comments_delete,
        name='comments_delete',
    ),
    path('<int:plan_pk>/likes/', views.likes, name='likes'),
    path('<int:plan_pk>/likes/<int:comment_pk>/', views.likes_comment, name='likes_comment'),
]

project1/project1/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from accounts import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('main/', include('main.urls')),
    path('accounts/', include('accounts.urls')),
    path('plans/', include('plans.urls')),
    path('issues/', include('issues.urls')),
    path('challenges/',include('challenges.urls')),
    path('algorithms/',include('algorithms.urls')),
    path(
        '<int:user_pk>/password/',
        views.change_password,
        name='change_password',
    ),
    # 이미지 경로 media 추가
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

project1/main/models.py
from django.db import models
from django.conf import settings


# Create your models here.
class Main(models.Model):
    user = models.ForeignKey(
        settings.AUTH_USER_MODEL, on_delete=models.CASCADE
    )
    # like_users = models.ManyToManyField(settings.AUTH_USER_MODEL, related_name='like_articles')
    title = models.CharField(max_length=10)
    content = models.TextField()
    image = models.ImageField(blank=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)


class Comment(models.Model):
    main = models.ForeignKey(Main, on_delete=models.CASCADE)
    user = models.ForeignKey(
        settings.AUTH_USER_MODEL, on_delete=models.CASCADE,
        related_name='main_comments'
    )
    content = models.CharField(max_length=200)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

project1/main/forms.py
from django import forms
from .models import Main, Comment


class MainForm(forms.ModelForm):
    class Meta:
        model = Main
        exclude = ('user',)


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('content',)

project1/main/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required
from .models import Main
from plans.models import Plan
from issues.models import Issue
from challenges.models import Challenge
from algorithms.models import Algorithm
from datetime import datetime
from .forms import MainForm, CommentForm
# Create your views here.
def index(request):
    mains = Main.objects.all()
    plans = Plan.objects.all()
    challenges = Challenge.objects.all()
    issues = Issue.objects.all()
    algorithms = Algorithm.objects.all()
    now = datetime.now()
    today_challenge = []
    for challenge in challenges:
        if challenge.created_at.date() == now.date():
            today_challenge.append(challenge)
    context = {
        'mains': mains,
        'plans': plans,
        'challenges' : today_challenge,
        'issues' : issues,
        'algorithms' : algorithms,
    }
    return render(request, 'main/index.html', context)


def detail(request, pk):
    main = Main.objects.get(pk=pk)
    comment_form = CommentForm()
    comments = main.comment_set.all()
    context = {
        'main': main,
        'comment_form': comment_form,
        'comments': comments,
    }
    return render(request, 'main/detail.html', context)

def test(request):
    mains = Main.objects.all()
    context = {
        'mains': mains,
    }
    return render(request, 'main/test.html', context)

def test2(request):
    mains = Main.objects.all()
    context = {
        'mains': mains,
    }
    return render(request, 'main/test2.html', context)

project1/main/templates/main/detail.html
{% extends "base.html" %}

{% block content %}

{% endblock content %}

project1/main/templates/main/index.html
{% extends "base.html" %}
{% block css %}
  <link rel="preconnect" href="https://fonts.googleapis.com">
  <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
  <link href="https://fonts.googleapis.com/css2?family=Gowun+Dodum&display=swap" rel="stylesheet">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.2/css/bootstrap.min.css">

<style>
  .font {
    font-family: 'Gowun Dodum', sans-serif;
  }
</style>
{% endblock css %}
{% block content %}
{% load static %}

<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Main Page</title>

<link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link href="https://fonts.googleapis.com/css2?family=Russo+One&display=swap" rel="stylesheet">
  <article class='container my-5'>
    <div class='callout '>
      <div class="border border-0 py-5" style="height:300px">
        <h1 class="font_style text-light mx-3 mt-3 animate__animated animate__bounceInRight">
          <img src="{% static "planet4.png" %}" alt="moon" height="70px">
          STUDY LOG
          <img src="{% static "planet4.png" %}" alt="moon" height="70px">
        </h1>
          <h3 class='font_sub_style text-light m-3 animate__animated animate__bounceInRight animate__delay-1s'>Welcome To Visit Our Site</h3>
      </div>
    </div>
  </article>
</head>
<body>
<div class='container'>
  <div class='row'>
      {% comment %} Plan board {% endcomment %}
      <div class-'col-12'>
        <div class="border border-2 border-light rounded-3 p-2 my-2 border-opacity-75 " >
          <h2 class="mx-2 font card-title lh-lg text-light"> New Plan Posting <img src="{% static "planet8.png" %}" height='30px' alt=""></h2>
          <div class="border border-2 border-light rounded-3 p-3 m-2 border-opacity-75 ">
            <div class='text-light font'>
              {% if plans|length == 0%}
                <td class='' colspan='5'>
                  <p class=' text-light'>작성된 플랜이 없습니다.</p></td>
              {% else %}
              <ol class="">
                {% for plan in plans %}
                  <a href="{% url 'plans:detail' plan.pk %}">
                    <div class = 'd-flex justify-content-between align-items-center'>
                      <p class=' text-light fw-bold'>{{ plan.title }}</p>
                      <p class='text-light'>{{ plan.user.username }} | {{ plan.created_at | date:"Y-m-d H:i"}}</p>
                    </div>
                    <hr class="my-2 border border-light border-1 opacity-50">
                  </a>
                {% endfor %}
              </ol>
              {% endif %}
            </div>
          </div>  
        </div>
      </div>
      <div class-'col-12'>
        <div class="border border-2 border-light rounded-3 p-2 my-2 border-opacity-75 " >
          <h2 class="mx-2 font card-title lh-lg text-light"> Algorithm Posting <img src="{% static "planet8.png" %}" height='30px' alt=""></h2>
          <div class="border border-2 border-light rounded-3 p-3 m-2 border-opacity-75 ">
            <div class='text-light font'>
              {% if algorithms|length == 0 %}
                <td class='' colspan='5'>
                  <p class=' text-light'>작성된 게시물이 없습니다.</p></td>
              {% else %}
              <ol class="">
                {% for algorithm in algorithms %}
                  <a href="{% url 'algorithms:index' %}">
                    <div class = 'd-flex justify-content-between align-items-center'>
                      <p class=' text-light fw-bold'>{{ algorithm.problem.name }}</p>
                      <p class='text-light'>{{ algorithm.user.username }} | {{ algorithm.created_at | date:"Y-m-d H:i"}}</p>
                    </div>
                    <hr class="my-2 border border-light border-1 opacity-50">
                  </a>
                {% endfor %}
              </ol>
              {% endif %}
            </div>
          </div>  
        </div>
      </div>
      <div class-'col-12'>
        <div class="border border-2 border-light rounded-3 p-2 my-2 border-opacity-75 " >
          <h2 class="mx-2 font card-title lh-lg text-light"> New Issue Posting <img src="{% static "planet8.png" %}" height='30px' alt=""></h2>
          <div class="border border-2 border-light rounded-3 p-3 m-2 border-opacity-75 ">
            <div class='text-light font'>
              {% if plans|length == 0%}
                <td class='' colspan='5'>
                  <p class=' text-light'>작성된 게시물이 없습니다.</p></td>
              {% else %}
              <ol class="">
                {% for issue in issues %}
                  <a href="{% url 'issues:detail' issue.pk %}">
                    <div class = 'd-flex justify-content-between align-items-center'>
                      <p class=' text-light fw-bold'>{{ issue.title }}</p>
                      <p class='text-light'>{{ issue.user.username }} | {{ issue.created_at | date:"Y-m-d H:i"}}</p>
                    </div>
                    <hr class="my-2 border border-light border-1 opacity-50">
                  </a>
                {% endfor %}
              </ol>
              {% endif %}
            </div>
          </div>  
        </div>
      </div>
  </div>

  <div class='row'>
    <div class='col-8'>
      <div class="border border-2 border-light rounded p-2 my-2 border-opacity-75 " >
        <h2 class="mx-2 font card-title lh-lg text-light">Today Challenge <img src="{% static "planet2.png" %}" height='30px' alt=""></h2>
          <div class="border border-2 border-light rounded p-3 m-2 border-opacity-75 ">
            <div class='text-light font'>
              <ol class="">
                {% for challenge in challenges %}
                    <a href="{% url 'challenges:index'%}">
                      <div class = 'd-flex justify-content-between align-items-center'>
                        <p class=' text-light fw-bold'>{{ challenge.title }}</p>
                        <p class='text-light'>{{ challenge.created_at | date:"Y-m-d H:i"}}</p>
                      </div>
                      <hr class="my-2 border border-light border-1 opacity-50">
                    </a>
                {% endfor %}
              </ol>
            </div>

          </div>  
      </div>
    </div>
    <div class='col-4'>
      <div class="border border-2 border-light rounded p-2 my-2 border-opacity-75 ">
        <h2 class="mx-2 card-title lh-lg text-light">Day 3 <img src="{% static "planet9.png" %}" height='30px' alt=""></h2>
        <br>
          <div class="border border-2 border-light rounded p-3 m-2 border-opacity-75">
          <br>
          <p class="card-text text-light"></p>
          </div>  
      </div>
    </div>
  </div>

{% endblock content %}


</body>
</html>

project1/main/templates/main/test.html
{% extends "base.html" %}

{% block content %}
{% load static %}
<head>
  <title >
    <p class=' text-light'>:: Calendar ::</p></title>
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Comfortaa&family=Russo+One&display=swap" rel="stylesheet">
    
    
  <style type="text/css">
    .font {
        font-family: 'Comfortaa', sans-serif;
    }
    a { 
        color:white;
        opacity: 0.7;
        text-decoration:none;
        text-align:center;      
    }
  
    .scriptCalendar > thead > tr { 
        align-items: center;
        text-align: center;
    }
    .scriptCalendar > thead > tr > td { 
        width:200px;
        height:100px; 
    }

    .scriptCalendar > thead > tr:first-child > td { 
        font-weight:bold; 
        font-size:40px;
        
    }
    .scriptCalendar > thead > tr:first-child { 
        display: flex;
    }
    {% comment %} sun ~ sat(첫째줄) {% endcomment %}
    .scriptCalendar > thead > tr:last-child > td { 
        display: flex;
        justify-content:center;
        align-items:center;
        background-color:#928E85;
        font-size:20px; 
        font-weight: bold; 
        height:50px;
        opacity:0.9;
        }
    .scriptCalendar > thead > tr:last-child  { 
        display: flex;
        }
    {% comment %} 날짜라인 {% endcomment %}
    .scriptCalendar > tbody > tr  { 
        display: flex;
    }    

    .scriptCalendar > tbody > tr > td { 
        align-items: baseline;
        color:white;
        background:black;
        width:200px;
        height:200px; 
        font-size:20px; 
        font-weight:bold;
        border: 1px solid rgba(255, 255, 244,0.7);
        text-align: start;
        padding-left: 5px;
    }

  </style>
  <script type="text/javascript">
      document.addEventListener("DOMContentLoaded", function() {
          buildCalendar();
      });
  
      var today = new Date(); // @param 전역 변수, 오늘 날짜 / 내 컴퓨터 로컬을 기준으로 today에 Date 객체를 넣어줌
      var date = new Date();  // @param 전역 변수, today의 Date를 세어주는 역할
  
      /**
       * @brief   이전달 버튼 클릭
       */
      function prevCalendar() {
          this.today = new Date(today.getFullYear(), today.getMonth() - 1, today.getDate());
          buildCalendar();    // @param 전월 캘린더 출력 요청
      }
  
      /**
       * @brief   다음달 버튼 클릭
       */
      function nextCalendar() {
          this.today = new Date(today.getFullYear(), today.getMonth() + 1, today.getDate());
          buildCalendar();    // @param 명월 캘린더 출력 요청
      }
  
      /**
       * @brief   캘린더 오픈
       * @details 날짜 값을 받아 캘린더 폼을 생성하고, 날짜값을 채워넣는다.
       */
      function buildCalendar() {
  
          let doMonth = new Date(today.getFullYear(), today.getMonth(), 1);
          let lastDate = new Date(today.getFullYear(), today.getMonth() + 1, 0);
  
          let tbCalendar = document.querySelector(".scriptCalendar > tbody");
  
          document.getElementById("calYear").innerText = today.getFullYear();                                  // @param YYYY월
          document.getElementById("calMonth").innerText = autoLeftPad((today.getMonth() + 1), 2);   // @param MM월
  
  
          // @details 이전 캘린더의 출력결과가 남아있다면, 이전 캘린더를 삭제한다.
          while(tbCalendar.rows.length > 0) {
              tbCalendar.deleteRow(tbCalendar.rows.length - 1);
          }
  
  
          // @param 첫번째 개행
          let row = tbCalendar.insertRow();
  
  
  
          // @param 날짜가 표기될 열의 증가값
          let dom = 1;
  
          // @details 시작일의 요일값( doMonth.getDay() ) + 해당월의 전체일( lastDate.getDate())을  더해준 값에서
          //               7로 나눈값을 올림( Math.ceil() )하고 다시 시작일의 요일값( doMonth.getDay() )을 빼준다.
          let daysLength = (Math.ceil((doMonth.getDay() + lastDate.getDate()) / 7) * 7) - doMonth.getDay();
  
          // @param 달력 출력
          // @details 시작값은 1일을 직접 지정하고 요일값( doMonth.getDay() )를 빼서 마이너스( - )로 for문을 시작한다.
          for(let day = 1 - doMonth.getDay(); daysLength >= day; day++) {
  
              let column = row.insertCell();
  
              // @param 평일( 전월일과 익월일의 데이터 제외 )
              if(Math.sign(day) == 1 && lastDate.getDate() >= day) {
  
  
                  // @param 평일 날짜 데이터 삽입
  
                  column.innerText = autoLeftPad(day, 2);
  
  
                  // @param 일요일인 경우
                  if(dom % 7 == 1) {
                      column.style.color = "#C51E3A";
                  }
  
                  // @param 토요일인 경우
                  if(dom % 7 == 0) {
                      column.style.color = "#4682B4";
                      row = tbCalendar.insertRow();   // @param 토요일이 지나면 다시 가로 행을 한줄 추가한다.
                  }
  
              }
  
              // @param 평일 전월일과 익월일의 데이터 날짜변경
              else {
                  let exceptDay = new Date(doMonth.getFullYear(), doMonth.getMonth(), day);
                  column.innerText = autoLeftPad(exceptDay.getDate(), 2);
                  column.style.color = "#A9A9A9";
              }
  
              // @brief   전월, 명월 음영처리
              // @details 현재년과 선택 년도가 같은경우
              if(today.getFullYear() == date.getFullYear()) {
  
                  // @details 현재월과 선택월이 같은경우
                  if(today.getMonth() == date.getMonth()) {
  
                      // @details 현재일보다 이전인 경우이면서 현재월에 포함되는 일인경우
                      if(date.getDate() > day && Math.sign(day) == 1) {
                          //column.style.backgroundColor = "#E5E5E5";
                      }
  
                      // @details 현재일보다 이후이면서 현재월에 포함되는 일인경우
                      else if(date.getDate() < day && lastDate.getDate() >= day) {
                          //column.style.backgroundColor = "black";
                          column.style.cursor = "pointer";
                          column.onclick = function(){ calendarChoiceDay(this); }
                      }
  
                      // @details 현재일인 경우
                      else if(date.getDate() == day) {
                          column.style.backgroundColor = "#36454F";
                          column.style.cursor = "pointer";
                          column.onclick = function(){ calendarChoiceDay(this); }
                      }
  
                  // @details 현재월보다 이전인경우
                  } else if(today.getMonth() < date.getMonth()) {
                      if(Math.sign(day) == 1 && day <= lastDate.getDate()) {
                          column.style.backgroundColor = "black";
                      }
                  }
  
                  // @details 현재월보다 이후인경우
                  else {
                      if(Math.sign(day) == 1 && day <= lastDate.getDate()) {
                          column.style.backgroundColor = "black";
                          column.style.cursor = "pointer";
                          column.onclick = function(){ calendarChoiceDay(this); }
                      }
                  }
              }
  
              // @details 선택한년도가 현재년도보다 작은경우
              else if(today.getFullYear() < date.getFullYear()) {
                  if(Math.sign(day) == 1 && day <= lastDate.getDate()) {
                      column.style.backgroundColor = "#E5E5E5";
                  }
              }
  
              // @details 선택한년도가 현재년도보다 큰경우
              else {
                  if(Math.sign(day) == 1 && day <= lastDate.getDate()) {
                      column.style.backgroundColor = "black";
                      column.style.cursor = "pointer";
                      column.onclick = function(){ calendarChoiceDay(this); }
                  }
              }
  
  
              dom++;
  
          }
      }
  
      /**
       * @brief   날짜 선택
       * @details 사용자가 선택한 날짜에 체크표시를 남긴다.
       */
      function calendarChoiceDay(column) {
  
          // @param 기존 선택일이 존재하는 경우 기존 선택일의 표시형식을 초기화 한다.
          if(document.getElementsByClassName("choiceDay")[0]) {
            console.log(parseInt(document.getElementsByClassName("choiceDay")[0].innerText),parseInt(today.getDate()) )
            if(parseInt(document.getElementsByClassName("choiceDay")[0].innerText) === parseInt(today.getDate())){
                document.getElementsByClassName("choiceDay")[0].style.backgroundColor = "#36454F";
                document.getElementsByClassName("choiceDay")[0].classList.remove("choiceDay");

            }
              document.getElementsByClassName("choiceDay")[0].style.backgroundColor = "black";
              document.getElementsByClassName("choiceDay")[0].classList.remove("choiceDay");
            
          }
  
          // @param 선택일 체크 표시
          column.style.backgroundColor = "#A9A9A9";
  
  
          // @param 선택일 클래스명 변경
          column.classList.add("choiceDay");
      }
  
      /**
       * @brief   숫자 두자릿수( 00 ) 변경
       * @details 자릿수가 한자리인 ( 1, 2, 3등 )의 값을 10, 11, 12등과 같은 두자리수 형식으로 맞추기위해 0을 붙인다.
       * @param   num     앞에 0을 붙일 숫자 값
       * @param   digit   글자의 자릿수를 지정 ( 2자릿수인 경우 00, 3자릿수인 경우 000 … )
       */
      function autoLeftPad(num, digit) {
          if(String(num).length < digit) {
              num = new Array(digit - String(num).length + 1).join("0") + num;
          }
          return num;
      }
  
  </script>
  </head>
  <body class="container">
    <div style="display:flex; justify-content:center;">
        <table class="scriptCalendar">
            <thead class="">
                <tr style="margin-left:395px; margin-bottom:100px">
                   
                        <td onClick="prevCalendar();" style="cursor:pointer; ">
                            <img src="{% static "Calendar/back_month.png" %}" alt="back_month" height="25px">
                        </td>
                        <td colspan="5">
                            <div>
                                <div>
                                    <span id="calYear" class="font fs-3 mx-2 text-white">YYYY </span>
                                </div>
                                <div>
                                    <span id="calMonth" class="font fs-1 text-white"> MM</span><p class="font"></p>
                                </div>
                            </div>
                        </td>
                        <td onClick="nextCalendar();" style="cursor:pointer;">
                            <img src="{% static "Calendar/next_month.png" %}" alt="next_month" height="25px">
                        </td>
                   
                </tr>
                <tr>
                    <td>Sun</td><td>Mon</td><td>Tue</td><td>Wed</td><td>Thu</td><td>Fri</td><td>Sat</td>
                </tr>
            </thead>
            <div>
                <tbody> 
          
                </tbody>
            </div>
        </table>
    </div>
  </body>

{% endblock content %}