project1/accounts/urls.py
from django.urls import path
from . import views
from accounts.views import UserRegistrationView, UserLoginView

app_name = 'accounts'
urlpatterns = [
    # path('login/', views.login, name='login'),
    path('login/', UserLoginView.as_view(), name='login'),         # 로그인
    path('logout/', views.logout, name='logout'),
    path('signup/',  UserRegistrationView.as_view(), name='signup'),
    path('delete/',views.delete, name='delete'),
    path('update/', views.update, name='update'),
    path('manage_board/', views.manage_board, name="manage_board"),
    path('follow/<int:user_pk>/', views.follow, name='following'),
    path('<int:user_pk>/', views.profile, name='profile'),
    
]

project1/issues/urls.py
from django.urls import path
from . import views

app_name = 'issues'
urlpatterns = [
    path('', views.index, name='index'),
    path('<int:pk>/', views.detail, name='detail'),
    path('create/', views.create, name='create'),
    path('<int:pk>/delete/', views.delete, name='delete'),
    path('<int:pk>/update/', views.update, name='update'),
    path('<int:pk>/comments/', views.comments_create, name='comments_create'),
    path(
        '<int:issue_pk>/comments/<int:comment_pk>/delete/',
        views.comments_delete,
        name='comments_delete',
    ),
    path('<int:issue_pk>/likes/', views.likes, name='likes'),
    path('<int:issue_pk>/likes/<int:comment_pk>/', views.likes_comment, name='likes_comment'),
]

project1/main/urls.py
from django.urls import path
from . import views

app_name = 'main'
urlpatterns = [
    path('', views.index, name='index'),
    path('<int:pk>/', views.detail, name='detail'),
    path('test/', views.test, name='test'),
    path('test2/', views.test2, name='test2'),

]

project1/project1/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from accounts import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('main/', include('main.urls')),
    path('accounts/', include('accounts.urls')),
    path('plans/', include('plans.urls')),
    path('issues/', include('issues.urls')),
    path('challenges/',include('challenges.urls')),
    path('algorithms/',include('algorithms.urls')),
    path(
        '<int:user_pk>/password/',
        views.change_password,
        name='change_password',
    ),
    # 이미지 경로 media 추가
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

project1/issues/models.py
from django.db import models
from django.conf import settings


# Create your models here.
class Issue(models.Model):
    user = models.ForeignKey(
        settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name='user_issues'
    )
    like_users = models.ManyToManyField(
        settings.AUTH_USER_MODEL, related_name='like_issues'
    )
    title = models.CharField(max_length=200)
    content = models.TextField()
    count = models.PositiveIntegerField(default=0)
    image = models.ImageField(blank=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    # def update_count(self):
    #     self.count = self.count + 1
    #     self.save()


class Comment(models.Model):
    issue = models.ForeignKey(Issue, on_delete=models.CASCADE, related_name='comments_issue')
    comment_user = models.ForeignKey(
        settings.AUTH_USER_MODEL, on_delete=models.CASCADE,
        related_name='issue_comments'
    )
    like_comment_users = models.ManyToManyField(
        settings.AUTH_USER_MODEL, related_name='like_comments_issue'
    )
    comment_content = models.CharField(max_length=200)
    comment_created_at = models.DateTimeField(auto_now_add=True)
    comment_updated_at = models.DateTimeField(auto_now=True)

project1/issues/forms.py
from django import forms
from .models import Issue, Comment


class IssueForm(forms.ModelForm):
    class Meta:
        model = Issue
        exclude = ('user', 'like_users','count')


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('comment_content',)

project1/issues/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required
from .models import Issue, Comment
from .forms import IssueForm, CommentForm
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.http import JsonResponse

# Create your views here.
@login_required
def index(request):
    sort = request.GET.get('sort', '')
    if sort == 'views':
        issues = Issue.objects.all().order_by('-count')
    elif sort == 'recently':
        issues = Issue.objects.all().order_by('-created_at')
    elif sort == 'unRecently':
        issues = Issue.objects.all().order_by('created_at')
    else:
        issues = Issue.objects.all()
    
    paginator = Paginator(issues,10)
    page_number = request.GET.get('page')
    posts = paginator.get_page(page_number)
    context = {
        'issues': posts,
    }
    return render(request, 'issues/index.html', context)

@login_required
def detail(request, pk):
    issue = Issue.objects.get(pk=pk)
    issue.count += 1
    issue.save()
    comment_form = CommentForm()
    comments = issue.comments_issue.all()
    context = {
        'issue': issue,
        'comment_form': comment_form,
        'comments': comments,
    }
    return render(request, 'issues/detail.html', context)


@login_required
def create(request):
    if request.method == 'POST':
        form = IssueForm(request.POST, request.FILES)
        if form.is_valid():
            issue = form.save(commit=False)
            issue.user = request.user
            form.save()
            return redirect('issues:detail', issue.pk)
    else:
        form = IssueForm()
    context = {
        'form': form,
    }
    return render(request, 'issues/create.html', context)


@login_required
def delete(request, pk):
    issue = Issue.objects.get(pk=pk)
    if request.user == issue.user:
        issue.delete()
    return redirect('issues:index')


@login_required
def update(request, pk):
    issue = Issue.objects.get(pk=pk)
    if request.user == issue.user:
        if request.method == 'POST':
            form = IssueForm(request.POST, request.FILES, instance=issue)
            if form.is_valid:
                p = form.save(commit=False)
                p.user = request.user
                form.save()
                return redirect('issues:detail', issue.pk)
        else:
            form = IssueForm(request.FILES, instance=issue)
    else:
        return redirect('issues:index')
    context = {
        'issue': issue,
        'form': form,
    }
    return render(request, 'issues/update.html', context)


@login_required
def comments_create(request, pk):
    issue = Issue.objects.get(pk=pk)
    comment_form = CommentForm(request.POST)
    if comment_form.is_valid():
        comment = comment_form.save(commit=False)
        comment.issue = issue
        comment.comment_user = request.user
        comment_form.save()
        return redirect('issues:detail', issue.pk)
    context = {
        'issue': issue,
        'comment_form': comment_form,
        'comment' : comment
    }
    return render(request, 'issues/detail.html', context)


def comments_delete(request, issue_pk, comment_pk):
    comment = Comment.objects.get(pk=comment_pk)
    if request.user == comment.comment_user:
        comment.delete()
    # return redirect('issues:detail', issue_pk)
    context = {

    }
    return JsonResponse(context)


def likes(request, issue_pk):
    issue = Issue.objects.get(pk=issue_pk)
    # if issue.like_users.filter(pk=request.user.pk).exists():
    #     issue.like_users.remove(request.user)
    # else:
    if not issue.like_users.filter(pk=request.user.pk):
        issue.like_users.add(request.user)
        is_liked = True
    else:
        issue.like_users.remove(request.user)
        is_liked = False

    issue.save()

    context = {
        'is_liked': is_liked,
        'likes_count': issue.like_users.count()
    }
    
    # return redirect('issues:detail', issue_pk)
    return JsonResponse(context)


def likes_comment(request, issue_pk, comment_pk):
    comment = Comment.objects.get(pk=comment_pk)
    # if issue.like_users.filter(pk=request.user.pk).exists():
    #     issue.like_users.remove(request.user)
    # else:
    if request.user not in comment.like_comment_users.all():
        comment.like_comment_users.add(request.user)
        is_comment_liked = True
    else:
        comment.like_comment_users.remove(request.user)
        is_comment_liked = False

    comment.save()

    context = {
        'is_comment_liked': is_comment_liked,
        'comment_likes_count': comment.like_comment_users.count()
    }
    
    # return redirect('issues:detail', issue_pk)
    return JsonResponse(context)


def issue_list(request):
    all_issues  = Issue.objects.all()
   
    page = request.GET.get('page', 1)
    paginator = Paginator(all_issues, 10)
    try:
        lines = paginator.page(page)
    except PageNotAnInteger:
        lines = paginator.page(1)
    except EmptyPage:
        lines = paginator.page(paginator.num_pages)

    context = {
        'samelines' : lines,
    }
 
    return render(request, 'issues/index.html', context)

project1/issues/templates/issues/create.html
{% extends "base.html" %}

{% block css %}
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.2/css/bootstrap.min.css">
{% endblock css %}

{% block content %}
{% comment %} <h1>PLAN CREATE PAGE</h1>
<form action="{% url "issues:create" %}" method="POST">
  {% csrf_token %}
  {{ form.as_p }}
  <input type="submit">
</form>
<hr>
<a href="{% url 'issues:index' %}">[back]</a> {% endcomment %}

<div class='container border bg-dark.bg-gradient p-3 rounded-5'>
  <h1 class='fw-bold text-white'>새 이슈 작성</h1>
  <form action="{% url "issues:create" %}" method="post" class="form-horizontal" enctype='multipart/form-data'>
    {% csrf_token %}                                     
    <input type="hidden" name="action" value="update">   
    <table class="table table-striped table-bordered table-dark">
      <tr>
        <th class='align-middle'>제목</th>                                    
        <td><input type="text" class="form-control" name="title"></td>
      </tr>
      <tr>
        <th class='align-middle'>작성자</th>                                   
        <td>{{ request.user }}</td>
      </tr>
      <tr>
      <tr>
        <th class='align-middle'>사진 업로드</th>                                    
        <td><input type="file" rows="10" class="form-control" name="image"></input></td>
      </tr>
      <tr>
        <th class='align-middle'>내용</th>                                    
        <td><textarea rows="10" class="form-control" name="content"></textarea></td>
      </tr>
    </table>
    <div class='d-flex justify-content-between'>
      <a href="{% url "issues:index" %}"><button class="btn btn btn-light text-dark mouse fw-bold" type="button">뒤로가기</button></a>
      <button class="btn btn-light text-dark mouse fw-bold" id="btn_cursor" type="submit">저장</button>
    </div>
    </form>

</div>

{% endblock content %}

project1/issues/templates/issues/detail.html
{% extends "base.html" %}
{% load static %}
{% block css %}
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Gowun+Dodum&display=swap" rel="stylesheet">

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.2/css/bootstrap.min.css">
    <style>
        .font {
          font-family: 'Gowun Dodum', sans-serif;
        }

      </style>
    {% endblock css %}

{% block content %}
    
    <div class='container border bg-dark.bg-gradient p-3 rounded-5'>
        <a href="{% url "issues:index" %}">
            <h1 class='font fw-bold text-white'>ISSUE BOARD</h1>
        </a>

        <table class="table table-striped table-bordered table-dark">
            <tr>
                <th class='font col-md-2 align-middle fs-1' colspan='2'>{{ issue.title }}</th>
            </tr>
            <tr>
                <div>
                    <td class='col-md-12 d-flex justify-content-between' colspan='2'>
                        <div>
                            {% comment %} <img src={% static "logo.png" %} alt="logo_medal.png" width="10" height="12">&nbsp;{{ issue.user.username }} &nbsp;|&nbsp; {% endcomment %}
                            <img src="{% static 'Rank/'|add:issue.user.beakjoon_rank|add:'.png' %}" width="27" height="27" alt="asd">&nbsp;<a href="{% url "accounts:profile" issue.user.pk %}">{{ issue.user.username }}</a> &nbsp;|&nbsp;
                            <img src={% static "hit_img.png" %} alt="logo_medal.png" width="18" height="13">&nbsp;<span>{{ issue.count }}</span> &nbsp;|&nbsp;
                            <img src={% static "comment_img.png" %} alt="logo_medal.png" width="18" height="15">&nbsp;<span id="cnt2">{{ issue.comments_issue.all|length }}</span> &nbsp;|&nbsp;
                            <img src={% static "like_img.png" %} alt="logo_medal.png" width="15" height="15">&nbsp; <span id="likes-count">{{ issue.like_users.all|length }}</span>
                        </div>
                        <div class ='font'>
                            <img src={% static "time2_img.png" %} alt="logo_medal.png" width="15" height="15">&nbsp;{{ issue.updated_at | date:"Y-m-d H:i" }}&nbsp;&nbsp;
                        </div>
                    </td>
                </div>

            </tr>

            {% if issue.image %}
            <tr>
                <td colspan='2'><img src="{{ issue.image.url }} " alt="" width=100% height=100%></td>
            </tr>
            {% else %}
            {% endif %}
            
            <tr>
                
                <td class='font' colspan='2' style="word-break:break-all">{{ issue.content | linebreaksbr }}</td>
            </tr>
        </table>
        {% if request.user == issue.user %}
        <div class='d-flex justify-content-between'>
            <div>
                {% comment %} <a href="{% url "issues:index" %}"><button class="btn btn btn-light text-dark mouse fw-bold" type="button">뒤로가기</button></a> {% endcomment %}
                <a class = 'mx-5' href="{% url "issues:index" %}">
                    <img src="{% static "back.png" %}" alt="back" height="20px">
                </a>
            </div>
            <div>
                {% comment %} <a href="{% url "issues:likes" issue.pk %}"><button class="btn btn-success mouse fw-bold" type="button"><img src={% static "like_img.png" %} alt="logo_medal.png" width="18" height="20">&nbsp;좋아요</button></a> {% endcomment %}
                {% comment %} <a class = 'mx-5' href="{% url "issues:likes" issue.pk %}">
                    <img src={% static "like3_img.png" %} alt="like_medal.png" height="20">
                </a> {% endcomment %}
                <a class = 'mx-5 likeA btn' data-issue-id="{{ issue.pk }}">
                    <img src={% static "like3_img.png" %} alt="like_medal.png" height="20">
                </a>
                {% comment %} <a href="{% url "issues:update" issue.pk %}" enctype='multipart/form-data'><button class="btn btn btn-light text-dark mouse fw-bold btn-sm" type="button">수정</button></a> {% endcomment %}

                <a class = 'mx-5' href="{% url "issues:update" issue.pk %}" enctype='multipart/form-data'>
                    <img src={% static "update.png" %} alt="like_medal.png" height="20">
                </a>
                {% comment %} <a href="{% url "issues:delete" issue.pk %}"><button class="btn btn btn-danger mouse fw-bold btn-sm" type="button">삭제</button></a> {% endcomment %}
                <a class = 'mx-5' href="{% url "issues:delete" issue.pk %}">
                    <img src={% static "trash.png" %} alt="like_medal.png" height="18">
                </a>
            </div>

            
        </div>
        {% else %}
        <div class='d-flex justify-content-between'>
            <a href="{% url "issues:index" %}"><button class="btn btn btn-light text-dark mouse fw-bold" id="btn_cursor" type="button">뒤로가기</button></a>
            <a class = 'mx-5 likeA btn' data-issue-id="{{ issue.pk }}">
                <img src={% static "like3_img.png" %} alt="like_medal.png" height="20">
            </a>

        </div>
        {% endif %}
        
        <hr class='border-4'>
        <div>
            <h5 id="commentCnt" class='fw-bold text-white font'>댓글 <span id="commentNum">{{ issue.comments_issue.all|length }}</span>개</h5>
            <form action="{% url "issues:comments_create" issue.pk %}" method="post" class="form-horizontal">
                {% csrf_token %}                                     
                <input type="hidden" name="action" value="update">   
                                  
                <textarea rows="3" class="form-control" name="comment_content"></textarea>

                <br>
                  
                <button class="btn btn-light text-dark mouse fw-bold font " id="btn_cursor" type="submit">댓글 작성</button>
                
                </form>
        </div>
        <br>
        <div id="comment-div">
            
                {% if issue.comments_issue.all|length %}
                    {% for comment in issue.comments_issue.all %}
                        <table id="comment-{{comment.pk}}" class="table table-striped table-bordered table-dark">
                            <tr>
                                <td class='col-md-12 d-flex justify-content-between' colspan='2'>
                                    <div>
                                        <img src={% static 'Rank/'|add:comment.comment_user.beakjoon_rank|add:'.png' %} width="20" height="20" alt="logo_medal.png" width="10" height="12">&nbsp;{{ comment.comment_user.username }} &nbsp;|&nbsp;
                                        <img src={% static "like_img.png" %} alt="logo_medal.png" width="15" height="15">&nbsp;<span id="comment-likes-count-{{comment.pk}}">{{ comment.like_comment_users.all|length }}</span>
                                    </div>
                                    <div class ='font'>
                                        <img src={% static "time2_img.png" %} alt="logo_medal.png" width="15" height="15">&nbsp;{{ issue.created_at | date:"Y-m-d H:i" }}&nbsp;&nbsp;
                                    </div>
                                </td>
                            </tr>
                            <tr>
                                <td class='d-flex justify-content-between '>
                                    <div class='align-self-center'>
                                        {{ comment.comment_content | linebreaksbr }}
                                    </div>
                                    <div class='d-flex'>
                                        <div class='align-self-center'>
                                            {% if request.user == comment.comment_user %}
                                            <a id="commentDelete" data-comment-id="{{ comment.pk }}" data-issue-id="{{ issue.pk }}" href=""><img src={% static "Board/delete.png" %} alt="unlike_img" height="30"></a>
                                            {% endif %}
                                            {% if request.user in comment.like_comment_users.all%}
                                                <a class="commentLike" data-comment-id="{{ comment.pk }}" data-issue-id="{{ issue.pk }}"><img id="imgTag-{{comment.pk}}" src={% static "Board/unlike.png" %} alt="unlike_img" height="30">&nbsp;</a>
                                            {% else %}
                                                <a class="commentLike" data-comment-id="{{ comment.pk }}" data-issue-id="{{ issue.pk }}"><img id="imgTag-{{comment.pk}}" src={% static "Board/like.png" %} alt="unlike_img"  height="30">&nbsp;</a>
                                            {% endif %}
                                            {% comment %} <a class="commentLike" data-comment-id="{{ comment.pk }}" data-issue-id="{{ issue.pk }}"><img src={% static "Board/like.png" %} alt="unlike_img"  height="30">&nbsp;</a> {% endcomment %}
                                        </div>
                                        
                                    </div>
                                </td>
                                
                            </tr>
                        </table>    
                    {% endfor %}
                {% else %}
                {% endif %}

            




        </div>
    </div>



    <script src="https://cdn.jsdelivr.net/npm/axios/dist/axios.min.js"></script>

    <script>


        const formTags = document.querySelector(".likeA")
        const commentTag = document.querySelectorAll(".commentLike")
        const commentDeleteTag = document.querySelectorAll("#commentDelete")
        

        formTags.addEventListener("click", function(event){
            event.preventDefault()
            console.log("dddsadasd")
            const issueId = formTags.dataset.issueId

            axios({
                method: "GET",
                url: `/issues/${issueId}/likes/`,

                })
                .then((response)=>{
                    const isLiked = response.data.is_liked
                    const likesCountTag = document.querySelector("#likes-count")
                    likesCountTag.textContent = response.data.likes_count
                })
                .catch((error)=>{
                    console.log("error")
                })
        })

        commentDeleteTag.forEach((commentDeleteTag) => {
            commentDeleteTag.addEventListener("click", function(event){
                event.preventDefault()
                const issueId = commentDeleteTag.dataset.issueId
                const commentId = commentDeleteTag.dataset.commentId

                axios({
                    method: "GET",
                    url: `/issues/${issueId}/comments/${commentId}/delete/`,
                })
                .then((response) => {
                    console.log('ok')
                    const deleteComment = document.querySelector(`#comment-${commentId}`)
                    const commentDiv = document.querySelector('#comment-div')
                    
                    commentDiv.removeChild(deleteComment)

                    const cntTag = document.querySelector('#commentNum')
                    const cntTag2 = document.querySelector('#cnt2')
                    let cnt = parseInt(cntTag.textContent)
                    let cnt2 = parseInt(cntTag2.textContent)
                    cnt--
                    cnt2--
                    cntTag.textContent = cnt
                    cntTag2.textContent = cnt2

                    
                    
                })
                .catch((error) => {
                    console.log(error)
                })
            })
        })


        commentTag.forEach((commentTag)=>{
            commentTag.addEventListener("click", function(event){
                event.preventDefault()
                const issueId = commentTag.dataset.issueId
                const commentId = commentTag.dataset.commentId
    
                axios({
                    method: "GET",
                    url: `/issues/${issueId}/likes/${commentId}/`,
                })
                .then((response)=>{
                    const isCommentLiked = response.data.is_comment_liked
                    const commentLikesCountTag = document.querySelector(`#comment-likes-count-${commentId}`)
                    commentLikesCountTag.textContent = response.data.comment_likes_count
                    console.log(response.data.comment_likes_count)
                    const imgTag = document.querySelector(`#imgTag-${commentId}`)
                    if (response.data.is_comment_liked){
                        console.log("dddddd")
                        imgTag.setAttribute("src", "{% static "Board/unlike.png" %}")
                    }
                    else{
                        imgTag.setAttribute("src", "{% static "Board/like.png" %}")
                    }

                    
                
                })
                .catch((error)=>{
                    console.log("error")
                })
            })
        })
        

    </script>

{% endblock content %}

project1/issues/templates/issues/index.html
{% extends "base.html" %}
{% load static %}

{% block css %}
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Gowun+Dodum&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.2/css/bootstrap.min.css">
    <style type="text/css">
        tbody > tr {cursor: pointer;}
        table {
            border-radius: 10px;
        }
        div {
            border-radius: 10px;
        }
        .font {
          font-family: 'Gowun Dodum', sans-serif;
        }

        .container {
            margin-top : 8%;
        }
    </style>
{% endblock css %}

{% block content %}
<div class='container border bg-dark.bg-gradient p-3 rounded-5'>
    <h1 class='font fw-bold text-white animate__animated animate__headShake'>
        ISSUE BOARD
    </h1>
    <table class='table table-hover table-responsive table-dark rounded-pill'>
        <thead>
            <tr>
                <th class='font fw-bold col-md-5 text-center fs-3' scope="col">Content</th>
                <th class='font fw-bold col-md-3 text-center fs-3' scope="col">Writer</th>
                <th class='font fw-bold col-md-2 text-center fs-3' scope="col">Upload Date</th>
                <th class='font fw-bold col-md-1 text-center fs-3' scope="col">Likes</th>
                <th class='font fw-bold col-md-1 text-center fs-3' scope="col">Views</th>
            </tr>
        </thead>
        <tbody class="table-group-divider">
            {% if issues|length == 0%}
                <td class='text-center' colspan='5'>아직 이슈가 업데이트 되지 않았어요!</td>
            {% else %}
            {% for issue in issues %}
            <tr onclick="location.href='{% url "issues:detail" issue.pk%}'">
                <td>{{ issue.title }}</td>
                {% comment %} <td class='text-center'><img src={% static "logo.png" %} alt="logo_medal.png" width="10" height="12">&nbsp;{{ issue.user.username }}</td> {% endcomment %}
                <td class='text-center'><img src="{% static 'Rank/'|add:issue.user.beakjoon_rank|add:'.png' %}" width="27" height="27" alt="asd">&nbsp;<a href="{% url "accounts:profile" issue.user.pk %}">{{ issue.user.username }}</a></td>
                <td class='text-center'>{{ issue.created_at | date:"Y-m-d H:i"}}</td>
                <td class='text-center'>{{ issue.like_users.all | length }}</td>
                <td class='text-center'>{{ issue.count }}</td>
            </tr>
            {% endfor %}
            {% endif %}

        </tbody>
    </table>
    {% comment %} <a href="{% url "issues:create" %}" class='btn btn btn-light text-dark mouse fw-bold btn-block col-3' type='button'>새 플랜 작성</a> {% endcomment %}
    <div class="d-flex justify-content-between">
      <div>
        <form method="GET" action="{% url "issues:index" %}" id="sort">
          <div class="col-4 d-flex">
            <select name="sort" id="sort" type="submit" >
              <option value="recently" id="recently" type="submit">최신순</option>
              <option value="unRecently" id="unRecently" type="submit">오래된순</option>
              <option value="views" id="likes" type="submit">조회순</option>
              {% comment %} <option value="comments" id="comments">댓글순</option> {% endcomment %}
            </select>
            <button class="ms-2 text-light btn btn-secondary font" type="submit" value="">정렬</button>
          </div>
      </div>
      <a href="{% url "issues:create" %}" enctype='multipart/form-data'><button class='text-light btn btn-secondary font' id="btn_cursor" type='button'>글쓰기</button></a>
    </div>


    <div class="row mt-2 align-self-center">
        <div class="col-12">
          <nav aria-label="Page navigation example">
            <ul class="pagination justify-content-center">
              {% if issues.has_previous %}
                <li class="page-item">
                  <a class="page-link text-secondary bg-dark border-0" href="?page={{ issues.previous_page_number }}">&laquo;</a>
                </li>
              {% else %}
                <li class="page-item disabled">
                  <a class="page-link text-secondary bg-dark border-0" href="#" tabindex="-1" aria-disabled="True">&laquo;</a>
                </li>
              {% endif %}
              {% for i in issues.paginator.page_range %}
                {% if issues.number == i %}
                  <li class="page-item active text-light bg-dark border-0" aria-current="page">
                    <span class="page-link text-light bg-dark border-0">
                      {{ i }}
                      <span class="sr-only"></span>
                    </span>
                  </li>
                {% else %}
                  <li class="page-item text-secondary bg-dark border-0"><a class="page-link text-secondary bg-dark border-0" href="?page={{ i }}">{{ i }}</a></li>
                {% endif %}
              {% endfor %}
              {% if issues.has_next %}
                <li class="page-item">
                  <a class="page-link text-secondary bg-dark border-0" href="?page={{ issues.next_page_number }}">&raquo;</a>
                </li>
              {% else %}
                <li class="page-item disabled">
                  <a class="page-link text-secondary bg-dark border-0" href="#" tabindex="-1" aria-disabled="True">&raquo;</a>
                </li>
              {% endif %}
            </ul>
          </nav>
        </div>
      </div>
</div>
{% endblock content %}